import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import AppProvider from "@/app/provider";
import AppHeader from "@/components/layouts/app-header";
import AuthControls from "@/features/auth/components/auth-controls";

import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  // TODO: Update to something more appropriate
  title: "Beverly Ristow",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProvider>
          <AppHeader>
            <AuthControls />
          </AppHeader>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
